#!/bin/bash
version="0.4.1"

usage ()
{
	echo \
'Usage: display-visor [-f] [-i] [-l [switch]]

	-f, --feh	Run feh bg script.
                         Executes ~/.fehbg upon completion.
	-i, --i3	Test for i3wm instance.
                         For avoiding conflict with multiple environments.
	-l, --lid	Check laptop lid status.
                         Ignored/Assumed closed if not given.
                         It is possible to specify switch. Defaults to 'LID0'
                         If unsure, look under /proc/acpi/button/lid/...
	-v, --version	Print version info.

 Useful for setting monitor layouts on system login/resume/hotplug
 when using window managers that do not handle display settings.

 Depends on xorg-xrandr.

This is free software.
2015, Michael Heyns <https://github.com/beanaroo>
'
}

handle_args ()
{
	while [ "$1" != "" ]; do
		case $1 in
			-h | --help )		usage
								exit
								;;
			-f | --feh )		fehbg=true
								;;
			-i | --i3 )			i3test=true
								;;
			-l | --lid )    	lidtest=true
                                lidswitch=${2:-LID0}
                                lidstatus=$(cat /proc/acpi/button/lid/$lidswitch/state 2>/dev/null | awk '{print $NF}')
                                shift
								;;
			-v | --version )	echo "display-visor $version"
								exit
								;;
			* )				usage
								exit 1
								;;
		esac
		shift
	done
}


## Error Handling
handle_err ()
{
    # Test for running Xorg server
    if [ -z "$(ps -C Xorg --no-headers)" ]; then
        echo "$prefix No Xorg server found. Exiting..."
        exit 1
    fi

    # Test for running instance of i3
    if [ "$i3test" == "true" -a -z "$(ps -C i3 --no-headers)" ]; then
        echo "$prefix i3wm not running. Exiting..."
        exit 1
    fi

    # Test for valid laptop lid status.
    if [ "$lidtest" == "true" -a -z "$lidstatus" ]; then
        echo "$prefix Laptop lid switch $lidswitch not found. Exiting..."
        exit 1
    fi
}

## Declare Output Devices
declare_outputs ()
{
    devices=$(find /sys/class/drm/*/status)
    while read l ; do
        dir=$(dirname $l)
        status=$(cat $l)
        dev=$(echo $dir | cut -d\- -f 2-)

        if [ $(expr match  $dev "HDMI") != "0" ]; then
            dev=HDMI${dev#HDMI-?-}
        else
            dev=$(echo $dev | tr -d '-')
        fi

        if [ "connected" == "$status" ]; then
            echo "$prefix $dev connected"
            declare -gA $dev="yes"
        fi
    done <<< "$devices"
}

## Configure monitors for closed lid
config_closed_lid ()
{
    if [ "$lidstatus" == "closed" ]; then
        echo "$prefix Laptop lid is closed"
    elif [ -n "$eDP1" -a -z "$lidtest" ]; then
        echo "$prefix Laptop display will be ignored unless -l option is set"
    fi
    if [ -n "$DP1-2" ]; then
        echo "$prefix SETTING: DP1-2 (Primary)"
        xrandr --output eDP1 --off \
               --output DP1-2 --auto --primary
    else
        echo "$prefix No external monitors are plugged in"
        xrandr --output DP1-2 --off \
               --output eDP1 --auto --primary
    fi
}

## Configure monitors for open lid
config_open_lid ()
{
    echo "$prefix Laptop lid is open"
    if [ -n "$DP1-2" ]; then
        echo "$prefix SETTING: eDP1 (Left) - DP1-2 (Primary)"
        xrandr --output eDP1 --auto --noprimary \
               --output DP1-2 --mode 3440x1440 --auto --primary --right-of eDP1
    else
        echo "$prefix No external monitors are plugged in"
        xrandr --output DP1-2 --off \
               --output eDP1 --auto --primary
    fi
}

configure_displays ()
{

    handle_err

    # refresh the lidstatus state
    if [ "$lidtest" == "true" ]; then
        lidstatus=$(cat /proc/acpi/button/lid/$lidswitch/state 2>/dev/null | awk '{print $NF}')
    fi

    declare_outputs

    if [ -z "$lidstatus" -o "$lidstatus" == "closed" ]; then
        config_closed_lid
    elif [ "$lidstatus" == "open" ]; then
        config_open_lid
    fi

    # Run .fehbg script if -f argument is given.
    if [ "$fehbg" == "true" ]; then
        if [ -x $HOME/.fehbg ]; then
            echo "$prefix Setting background using .fehbg."
            $($HOME/.fehbg 2>/dev/null)
        else
            echo ".$prefix Failed to execute ~/.fehbg script. Use 'feh --bg-xxx' to generate one."
        fi
    fi

	# FIXME: Prevent segfault occurring from simultanious signals. -- Issue #5 --
	sleep 2

}

#-----------#
#   Begin   #
#-----------#

# Set exit signal trap.
trap "echo 'Received interrupt. Exiting...' ; exit" SIGHUP SIGINT SIGQUIT

# Log output.
#prefix='[ display-visor: ]:'
exec 1> >(logger -s -t "display-visor") 2>&1

# Handle arguments.
handle_args "$@"

# Configure displays upon initialization.
configure_displays

# Set reconfigure trap.
trap "echo 'Received signal. Reconfiguring displays.' ; configure_displays" RTMIN+5

# Wait for signals
while :
do
    sleep 60 &
    wait
done
